### PR TITLE
OTP Concurrency Homework

### PR DESCRIPTION
**Pull request by SophieDeBenedetto**
Per this issue https://github.com/elixirschool/elixirschool/issues/2295, this PR adds homework for the OTP Concurrency lesson on elixirschool.com. 

We will close the original PR that added assignments to the `elixirschool/elixirschool` repo in favor of placing test-driven homework assignments in this repo. 

This PR:
* Adds a new directory, `lessons/`, under which we will place all homework assignments that correspond to Elixir School lessons
* Introduces a new homework assignment `lessons/otp-concurrency/simple-queue` with a test suite
* Moves the `simple_bank` assignment into` lessons/otp-concurrency/simple-bank`
* Provides some fixes to the simple bank starter-code and test suite 
* Adds a README for each homework assignment in their respective directories

The solutions for both assignments can be found on the [solution branch](https://github.com/elixirschool/homework/tree/solution)

### CODE REVIEW

**Comment by SophieDeBenedetto** [comment]
> Hi, thanks for this! Nice to see the lesson being compiled to an actual elixir project.
> 
> In terms of the frontend integration, I haven't found a cool, automated way of joining the _lessons_ and _homeworks_ in Jekyll. Should we edit the markdown content separately for every new homework? How would you approach this?

Hello! Yep I think editing the lesson content manually and opening a PR is the way to go. I think in the past we had discussed adding a call-out/formatted box or something to the end of the lesson briefly introducing the homework assignment and linking to the homework repo? Then, as we add more homework, we can copy-paste that content into each corresponding lesson and just make whatever minor changes. 

Let me know how that sounds and if you have any other questions!

**Comment by SophieDeBenedetto** [comment]
_also_, working on the solution of the simple bank hw was surprisingly challenging! I'm not working with Elixir in production anymore and I was _so_ rusty. I learned/was reminded of a lot and had a ton of fun doing it 🚀 🚀 🚀 Excited to get this in front of Elixir School readers!

**Comment by doomspork** [comment]
Some of these examples may need to be tweaked. I was doing a brain dump of sorts, they may not be all be the same level of difficulty.

I am _very_ excited to get these in front of folks and to see new homeworks start coming in. This is going to be a huge benefit to reads and the community as a whole.

Great work you two! Cheers :tada:

**Comment by SophieDeBenedetto** [comment]
Gonna merge this now and once we PR/merge the updates to the lesson itself on `elixirschool/elixirschool`, we can publicize.

**Pull request merged**
